export const WORKFLOW_V2_ACTION_HANDLER_NAMES = {
  "workflow.v2.plan.preview": "workflowV2PlanPreview",
  "workflow.v2.plan.create": "workflowV2PlanCreate",
  "workflow.supervisor.readiness.preview": "workflowSupervisorReadinessPreview",
  "workflow.v2.readiness.preview": "workflowV2ReadinessPreview",
  "workflow.supervisor.next_actions.preview": "workflowSupervisorNextActionsPreview",
  "workflow.archive.checkpoint.preview": "workflowArchiveCheckpointPreview",
  "workflow.archive.checkpoint": "workflowArchiveCheckpoint",
  "workflow.supervisor.checkpoint.preview": "workflowSupervisorCheckpointPreview",
  "workflow.supervisor.checkpoint": "workflowSupervisorCheckpoint",
  "workflow.supervisor.closeout.preview": "workflowSupervisorCloseoutPreview",
  "workflow.supervisor.closeout": "workflowSupervisorCloseout",
  "workflow.supervisor.report.preview": "workflowSupervisorReportPreview",
  "workflow.supervisor.report": "workflowSupervisorReport",
  "workflow.v2.next_actions.preview": "workflowSupervisorNextActionsPreview",
  "workflow.v2.info_stack.preview": "workflowV2InfoStackPreview",
  "workflow.v2.info_stack.record": "workflowV2InfoStackRecord",
  "workflow.v2.info_stack.read": "workflowV2InfoStackRead",
  "workflow.v2.read_receipt.record": "workflowV2ReadReceiptRecord",
  "workflow.v2.notification.preview": "workflowV2NotificationPreview",
  "workflow.v2.worker_backend.preflight": "workflowV2WorkerBackendPreflight",
  "workflow.v2.worker_backend_preflight.record": "workflowV2WorkerBackendPreflightRecord",
  "workflow.v2.worker_spawn.preview": "workflowV2WorkerSpawnPreview",
  "workflow.v2.worker_spawn.create": "workflowV2WorkerSpawnCreate",
  "workflow.v2.worker_lifecycle.preview": "workflowV2WorkerLifecyclePreview",
  "workflow.v2.worker_handoff.preview": "workflowV2WorkerHandoffPreview",
  "workflow.v2.worker_handoff.record": "workflowV2WorkerHandoffRecord",
  "workflow.v2.worker_retire.preview": "workflowV2WorkerRetirePreview",
  "workflow.v2.worker_retire.record": "workflowV2WorkerRetireRecord",
  "workflow.v2.worker_successor.preview": "workflowV2WorkerSuccessorPreview",
  "workflow.v2.worker_successor.create": "workflowV2WorkerSuccessorCreate",
  "workflow.v2.control_loop.preview": "workflowV2ControlLoopPreview",
  "workflow.v2.control_loop.tick": "workflowV2ControlLoopTick",
  "workflow.v2.worker_adapter_job.preview": "workflowV2WorkerAdapterJobPreview",
  "workflow.v2.worker_adapter_job.record": "workflowV2WorkerAdapterJobRecord",
  "workflow.v2.worker_adapter_job.list": "workflowV2WorkerAdapterJobList",
  "workflow.v2.worker_adapter_job.claim": "workflowV2WorkerAdapterJobClaim",
  "workflow.v2.worker_adapter_job.heartbeat": "workflowV2WorkerAdapterJobHeartbeat",
  "workflow.v2.worker_adapter_job.release": "workflowV2WorkerAdapterJobRelease",
  "workflow.v2.worker_adapter_job.fail": "workflowV2WorkerAdapterJobFail",
  "workflow.v2.adapter_runner.preview": "workflowV2AdapterRunnerPreview",
  "workflow.v2.adapter_runner.wrapper_contract.preview": "workflowV2AdapterRunnerWrapperContractPreview",
  "workflow.v2.adapter_runner.service_plan.preview": "workflowV2AdapterRunnerServicePlanPreview",
  "workflow.v2.adapter_runner.drain_readiness.preview": "workflowV2AdapterRunnerDrainReadinessPreview",
  "workflow.v2.adapter_runner.drain": "workflowV2AdapterRunnerDrain",
  "workflow.v2.worker_result.submit.preview": "workflowV2WorkerResultSubmitPreview",
  "workflow.v2.worker_result.submit": "workflowV2WorkerResultSubmit",
  "workflow.v2.worker_result.fail.preview": "workflowV2WorkerResultFailPreview",
  "workflow.v2.worker_result.fail": "workflowV2WorkerResultFail",
  "workflow.v2.manager_review.record": "workflowV2ManagerReviewRecord",
  "workflow.v2.owner_review.preview": "workflowV2OwnerReviewPreview",
  "workflow.v2.owner_review.record": "workflowV2OwnerReviewRecord",
  "workflow.v2.task_group_package.preview": "workflowV2TaskGroupPackagePreview",
  "workflow.v2.task_group_package.record": "workflowV2TaskGroupPackageRecord",
  "workflow.v2.governance_audit.preview": "workflowV2GovernanceAuditPreview",
  "workflow.v2.governance_semantic_check.preview": "workflowV2GovernanceSemanticCheckPreview",
  "workflow.v2.governance_audit.record": "workflowV2GovernanceAuditRecord",
  "workflow.v2.protocol_audit.preview": "workflowV2ProtocolAuditPreview",
  "workflow.v2.protocol_audit.record": "workflowV2ProtocolAuditRecord",
  "workflow.v2.protocol_package_audit.preview": "workflowV2ProtocolPackageAuditPreview",
  "workflow.v2.human_gate_package.preview": "workflowV2HumanGatePackagePreview",
  "workflow.v2.human_gate_package.record": "workflowV2HumanGatePackageRecord",
  "workflow.v2.human_gate_request.preview": "workflowV2HumanGateRequestPreview",
  "workflow.v2.human_gate_request": "workflowV2HumanGateRequest",
  "workflow.v2.intervention_readiness.preview": "workflowV2InterventionReadinessPreview",
  "workflow.v2.intervention.readiness.preview": "workflowV2InterventionReadinessPreview",
  "workflow.v2.intervention_settlement.preview": "workflowV2InterventionSettlementPreview",
  "workflow.v2.intervention.settlement.preview": "workflowV2InterventionSettlementPreview",
  "workflow.v2.settlement.preview": "workflowV2InterventionSettlementPreview",
  "workflow.v2.pause.preview": "workflowV2InterventionReadinessPreview",
  "workflow.v2.resume.preview": "workflowV2InterventionReadinessPreview",
  "workflow.v2.stop.preview": "workflowV2InterventionReadinessPreview",
  "workflow.v2.terminate.preview": "workflowV2InterventionReadinessPreview",
  "workflow.v2.pause": "workflowV2InterventionExecute",
  "workflow.v2.resume": "workflowV2InterventionExecute",
  "workflow.v2.stop": "workflowV2InterventionExecute",
  "workflow.v2.terminate": "workflowV2InterventionExecute",
  "workflow.v2.evaluation_snapshot.preview": "workflowV2EvaluationSnapshotPreview",
  "workflow.v2.evaluation.record": "workflowV2EvaluationRecord",
  "workflow.v2.evaluation_compatibility.preview": "workflowV2EvaluationCompatibilityPreview",
  "workflow.v2.evaluation_migration.preview": "workflowV2EvaluationMigrationPreview",
  "workflow.v2.validate": "workflowV2Validate",
  "workflow.template.preview": "workflowTemplatePreview",
  "workflow.template.daily_trading_catalog.preview": "workflowTemplateDailyTradingCatalogPreview",
  "workflow.template.record_candidate": "workflowTemplateRecordCandidate",
  "workflow.template.search": "workflowTemplateSearch",
  "workflow.template.get": "workflowTemplateGet",
  "workflow.template.instantiate.preview": "workflowTemplateInstantiatePreview",
  "workflow.template.instantiate.record": "workflowTemplateInstantiateRecord",
  "workflow.template.eval.preview": "workflowTemplateEvalPreview",
  "workflow.template.eval.record": "workflowTemplateEvalRecord",
  "workflow.template.stats.refresh": "workflowTemplateStatsRefresh",
  "workflow.template.promote.preview": "workflowTemplatePromotePreview",
  "workflow.template.promote.record": "workflowTemplatePromoteRecord",
  "workflow.template.rollback.preview": "workflowTemplateRollbackPreview",
  "workflow.template.rollback.record": "workflowTemplateRollbackRecord",
  "workflow.template.extract.preview": "workflowTemplateExtractPreview",
  "workflow.template.extract.record": "workflowTemplateExtractRecord"
};

export function createWorkflowV2ActionRegistry(handlers = {}) {
  const entries = Object.entries(WORKFLOW_V2_ACTION_HANDLER_NAMES).map(([action, handlerName]) => {
    const handler = handlers[handlerName];
    if (typeof handler !== "function") {
      throw new Error(`Missing workflow v2 action handler: ${handlerName}`);
    }
    return [action, handler];
  });
  return new Map(entries);
}

export async function runWorkflowV2Action(registry, action, rootDir, input = {}, permissionDecision = null) {
  const handler = registry.get(action);
  if (!handler) return { handled: false, value: null };
  return { handled: true, value: await handler(rootDir, { ...input, action }, permissionDecision) };
}
